appoptics/appoptics-apm-go

README.md, examples/distributed_app/docker-compose.yml
My docker-compose (1.18.0) complains that this wasn't the right type. The yaml here was defining environment as one-item lists containing a map with a single key/value (I think; yaml can be confusing).
```
$ docker-compose build
...
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.alice.environment contains {"APPOPTICS_SERVICE_KEY": ""}, which is an invalid type, it should be a string
services.bob.environment contains {"APPOPTICS_SERVICE_KEY": ""}, which is an invalid type, it should be a string
services.caroljs.environment contains {"APPOPTICS_SERVICE_KEY": ""}, which is an invalid type, it should be a string
services.davepy.environment contains {"APPOPTICS_SERVICE_KEY": ""}, which is an invalid type, it should be a string
services.otto.environment contains …
```
=> Fix example's docker-compose.yml `environment` type

v1/ao/trace.go
This adds a SetStatus method to the Trace interface and implementations, and also adds support in `recordHTTPSpan` for passing an `int` status to `trace.AddEndArgs("Status", ...)` in addition to the existing support for a `*int`; without the latter fix, my program panicked inside `recordHTTPSpan()` when I passed an `int` to `trace.AddEndArgs("Status", ...)`.
=> Add SetStatus method to Trace

v1/ao/internal/reporter/reporter_grpc.go
default log level is ERROR so connection msgs won't be logged by default.
=> adjust log levels for connection related log messages

README.md
Fixes #22
A more detailed example showing how to use this repo's `opentracing` package to create a global tracer to be set as a global tracing object with `github.com/opentracing/opentracing-go`.
* Ambiguity around package names could produce dev confusion here.
* Documentation was referencing a deprecated function -- this PR fixes that too.
=> Add detailed example clarifying imports

v1/ao/Makefile, v1/ao/internal/reporter/oboe.go, v1/ao/internal/reporter/oboe_test.go, v1/ao/internal/reporter/reporter_grpc_test.go, v1/ao/internal/reporter/reporter_test.go, v1/ao/internal/reporter/utils.go, v1/ao/internal/reporter/version.go
For https://swicloud.atlassian.net/secure/RapidBoard.jspa?rapidView=88&projectKey=AO&modal=detail&selectedIssue=AO-8294
Basically it's a small improvement that we can use a single command `make VERSION=1.2.3 tag-and-release` to do the following work:
1. Replace the value of constant `initVersion`  with _1.2.3_ and commit it to the master branch
2. Tag the current commit point with the name `1.2.3`
The value of `initVersion` is used to report `Oboe.Go.Version`
=> AO-8294: agent versioning

v1/ao/internal/reporter/oboe.go
This PR is to fix the issue `Go: APPOPTICS_DEBUG_LEVEL docs and implementation are different` on Jira.
Now with this fix it supports both integers(for backward compatibility) and string values (which is case-insensitive, e.g., debug, INFO or Error)
=> AO-8242 Let APPOPTICS_DEBUG_LEVEL support string values

v1/ao/internal/reporter/reporter.go, v1/ao/internal/reporter/reporter_grpc.go, v1/ao/internal/reporter/reporter_test.go
Pull request for Jira issue AO-8243:
1. It will print an error message when the number of retries to post messages reaches a threshold (10 for now). There will also be a message for recovery then.
2. Removed `redirect` invocations in the error handling of `Post*` as it does nothing helpful.
3. Test cases for the changes
=> AO-8243 Proper logging for connections issues 

v1/ao/internal/reporter/metrics.go, v1/ao/internal/reporter/metrics_test.go
This pull request is for the Jira task: https://swicloud.atlassian.net/browse/AO-8007
Remove the files check (to make sure it's an EC2 instance) before we fetch the EC2 metadata.
1. Removed `isEC2Instance` and its test cases
2. Removed the global variable `cachedIsEC2Instance`
3. Created a helper function to cover both `getAWSInstanceID` and `getAWSInstanceZone`
4. Added test cases in `TestGetAWSMetadata`
=> AO-8007-Remove the files check for EC2 metadata

.travis.yml, README.md, examples/gin_app/gin_middleware.go, v1/ao/http_instrumentation.go, v1/ao/http_instrumentation_oboe_test.go, v1/ao/http_instrumentation_test.go, v1/ao/internal/reporter/context.go, v1/ao/internal/reporter/context_test.go, v1/ao/internal/reporter/event.go, v1/ao/internal/reporter/metrics.go, v1/ao/internal/reporter/metrics_test.go, v1/ao/internal/reporter/oboe.go, v1/ao/internal/reporter/reporter.go, v1/ao/internal/reporter/reporter_grpc.go, v1/ao/internal/reporter/reporter_test.go, v1/ao/internal/reporter/reporter_udp.go, v1/ao/internal/reporter/test_reporter.go, v1/ao/internal/reporter/utils.go, v1/ao/layer.go, v1/ao/trace.go
Jira link: https://swicloud.atlassian.net/browse/AO-7051
1. Added API for setting custom transaction names
2. Added the environment variable APPOPTICS_PREPEND_DOMAIN to control if the domain should be added to the transaction names
3. Streamlined the logic of getting transaction names
4. Other minor changes
PR for doc update: https://github.com/librato/ao-kb-docs/pull/463
=> AO-7051 Custom Transaction Name

v1/ao/http_instrumentation.go, v1/ao/http_instrumentation_oboe_test.go, v1/ao/http_instrumentation_test.go
From the spec:
Per the web request KV spec, the HTTP-Host KV is required and contains domain information, this should be used as the domain value. There is also an optional Forwarded-Host KV that if available should be used in preference over HTTP-Host.
=> AO-8587: Use X-Forwarded-Host as the domain if available

.travis.yml, README.md, v1/ao/cov.sh, v1/ao/http_instrumentation_oboe_test.go, v1/ao/http_instrumentation_test.go, v1/ao/internal/agent/agent.go, v1/ao/internal/agent/config.go, v1/ao/internal/agent/config_builder.go, v1/ao/internal/agent/config_builder_test.go, v1/ao/internal/agent/config_test.go, v1/ao/internal/agent/logging.go, v1/ao/internal/agent/logging_test.go, v1/ao/internal/reporter/context.go, v1/ao/internal/reporter/context_test.go, v1/ao/internal/reporter/event.go, v1/ao/internal/reporter/metrics.go, v1/ao/internal/reporter/metrics_linux.go, v1/ao/internal/reporter/oboe.go, v1/ao/internal/reporter/oboe_test.go, v1/ao/internal/reporter/reporter.go, v1/ao/internal/reporter/reporter_grpc.go, v1/ao/internal/reporter/reporter_grpc_test.go, v1/ao/internal/reporter/reporter_test.go, v1/ao/internal/reporter/reporter_udp.go, v1/ao/internal/reporter/test_reporter.go, v1/ao/internal/reporter/utils.go
What has been done:
1. Print all non-default configuration values in default level
2. Mask the service token while printing it
3. Refactored the code of configuration initialization and printing to avoid boilerplate (e.g., print non-default environment variable values everywhere). Now all the configurations are managed in a standalone package `agent`. Other packages can call the API provided by this package to get the current value of a specific configuration.
4. Changed the default print level from ERROR to WARN -- This is TBD. I think ERROR is too high as a default level, and it looks a bit weird to print the non-default configurations in ERROR level. However, it needs further discussion as the change breaks the backward-compatibility.
=> AO-8448 log overridden

v1/ao/internal/reporter/context.go, v1/ao/internal/reporter/metrics.go, v1/ao/internal/reporter/metrics_test.go, v1/ao/internal/reporter/oboe.go, v1/ao/internal/reporter/reporter_grpc.go, v1/ao/trace.go
Jira: https://swicloud.atlassian.net/browse/AO-8850
1. Refactored the transaction names map and reset it after reporting the metrics
2. Some minor fixes.
=> AO-8850: reset transaction names map in every metrics reporting cycle

.gitignore, .travis.yml, v1/ao/cov.sh, v1/ao/internal/agent/config_builder.go, v1/ao/internal/agent/config_test.go, v1/ao/internal/reporter/metrics.go, v1/ao/internal/reporter/reporter.go, v1/ao/internal/reporter/reporter_grpc.go, v1/ao/internal/reporter/reporter_grpc_test.go, v1/ao/internal/reporter/reporter_test.go, v1/ao/internal/reporter/reporter_udp.go, v1/ao/internal/reporter/test_reporter.go, v1/ao/internal/reporter/utils.go
See: https://swicloud.atlassian.net/browse/AO-8322
1. Tear down the reporter when INVALID_API_KEY is received. (so a few checks against the r.done channel)
2. Short-circuit events reporting in case of closed reporter.
3. Replaced reconnect AUTHORITY with a lock as there is a data race.
4. Use atomic for all operations to queue stats.
5. Fixed some data race issues.
6. Other minor improvements
=> AO-8322: improvement on error handlings

v1/contrib/grpc/interceptors.go
This adds a contrib directory, and a package providing gRPC interceptors for tracing gRPC services using AppOptics, adapted from work by @ggerrietts.
=> AO-8426 Add gRPC interceptors to contrib

v1/ao/trace.go
Talking to @seubert this relationship was confusing at first, so I added an extra sentence to the godoc to explain that Trace is a root Span with additional methods for helping to categorize inbound requests.
=> add explanation of Trace and Span relationship

v1/contrib/grpc/interceptors.go
My current setup using the client interceptor and server interceptor is resulting in the header being downcased when the server interceptor retrieves the metadata. I'm not sure what is causing this, but I think we should be checking for lowercase anyway unless there's something I don't know about case sensitive headers here.
Also, not sure that's the ideal way to check for both keys.
=> Check for lowercase header name as well

v1/ao/layer.go, v1/ao/layer_test.go
The main items are:
- Add `Spec` KV with value `error`
- Ensure all the error events have the mentioned KV
- Ensure `Layer` KV is reported if available
=> AO-9415: Error spec audit

v1/ao/internal/reporter/oboe.go, v1/ao/internal/reporter/oboe_test.go, v1/ao/internal/utils/version.go
Ref: https://swicloud.atlassian.net/browse/AO-10063
The following changes have been committed to this branch:
- trim the prefix `go` from the golang version string
- remvoe the prefix `v` from the AppOptics version string
- rename the event key `Go.Oboe.Version` to `Go.AppOptics.Version`
=> AO-10063: Fix Version Strings

v1/ao/trace.go, v1/ao/trace_test.go
Ref: https://swicloud.atlassian.net/browse/AO-10033
Attach the X-Trace ID to the HTTP header of every request, no matter whether it is sampled or not.
The commit removes the sampling check in `ExitMetadata` and make it returns the metadata unconditionally.
=> AO-10033: Per Request X-Trace ID

v1/ao/http_instrumentation_test.go, v1/ao/internal/reporter/methods.go, v1/ao/internal/reporter/methods_test.go, v1/ao/internal/reporter/mocks/Method.go, v1/ao/internal/reporter/reporter_grpc.go, v1/ao/internal/reporter/reporter_test.go
Ref: https://swicloud.atlassian.net/browse/AO-10071
The main purpose of this PR:
- add the second return value (`error`) to the API `ResultCode` to indicate if the RPC is issued successfully, or not yet issued at all. By this way the method `CallSummary` knows whether it can access the RPC result (if not yet called or failed the `.Resp` field may be a null pointer).
Some other fixes/improvements:
- print the error in the call summary if the RPC is not successful
- change the log level of failed RPC calls to WARNING (the default level)
- other minor fixes (e.g., inconsistent receiver names of the struct methods)
=> AO-10071: Fix Method APIs for unissued RPC requests

v1/ao/agent.go, v1/ao/agent_test.go, v1/ao/http_instrumentation.go, v1/ao/internal/reporter/oboe.go, v1/ao/internal/reporter/reporter.go, v1/ao/internal/reporter/reporter_grpc.go, v1/ao/trace.go
Ref: https://swicloud.atlassian.net/browse/AO-8851
Do the following action to short-circuit the tracing when the agent is closed:
- Do not create new traces
- Return false immediately in `WaitForReady` when the reporter is closed
- Skip sending `__Init` message
=> AO-8851: Short-circuit the tracing when the reporter is closed

README.md, v1/ao/internal/reporter/reporter_grpc.go
Minor fixes:
- Print the Go version in the log when the agent is started, so it won't need to ask for this information while diagnosing issues.
- Fix a code error in README: a right curly bracket is missing.  (Ref: https://swicloud.atlassian.net/browse/AO-8901)
=> AO-8901: print Go version in log, fix a code error in README

v1/ao/client_layer.go, v1/ao/client_layer_test.go
Add a mandatory KV `Spec`: "query"
See: https://github.com/librato/trace/blob/master/docs/specs/KV/query.md
=> AO-10140: Add Spec KV for query span

v1/ao/layer.go, v1/ao/opentracing/tracer.go
The changes:
- Fix data races of `spanImpl` methods
- Implement the method `SetOperationName`  by adding new methods to the Span interface
- Finish the function docs
Ref: https://swicloud.atlassian.net/browse/AO-10145
=> AO-10145: fix spanImpl methods

v1/ao/client_layer.go, v1/ao/client_layer_test.go, v1/ao/doc_test.go, v1/ao/http_client_instrumentation.go, v1/ao/http_instrumentation.go, v1/ao/http_instrumentation_test.go, v1/ao/internal/reporter/metrics.go, v1/ao/layer.go, v1/ao/layer_test.go, v1/ao/profile_test.go, v1/ao/trace.go, v1/ao/trace_test.go
Jira ticket: https://swicloud.atlassian.net/browse/AO-10162
The changes:
- add stacktrace in BeginSpan
- add stacktrace in Info
- add stacktrace in NewTrace / NewTraceFromID
- client spans (query, cache, rpc, etc)
- open to future extensions without breaking the old APIs
=> AO-10162: Optionally include backtrace in events

.codecov.yaml
Set `threshold` to `1` (means 1%) otherwise the codecov fails with even a little coverage decrease.
=> Change codecov success threshold

v1/ao/context.go, v1/ao/context_test.go, v1/ao/http_instrumentation.go
While benchmarking code that happened to invoke this library's TraceFromContext function I discovered that TraceFromContext was strangely allocating a single object on the heap in every invocation.
I added a benchmark and dug into it. `context.Value(...)` takes an `interface{}` type argument, and it seems that in order to pass `contextSpanKey` (which is in turn `type contextKeyT string`) as `interface{}`, a new interface is allocated on the heap.
Benchmark before:
```
$ go test -benchmem -bench BenchmarkTraceFromContextEmpty
...
BenchmarkTraceFromContextEmpty-12    	50000000	        34.6 ns/op	      16 B/op	       1 allocs/op
```
If we change `type contextKeyT string` to `type contextKeyT interface{}`, we can avoid this heap allocation:
```
$ go test -benchmem -bench …
```
=> Optimize TraceFromContext when context is empty

v1/ao/client_layer.go, v1/ao/client_layer_test.go
Add a new KV `Spec`=`rsc` to the RPC/HTTP/Cache Span event. This follows the Remote Service Call spec in https://github.com/librato/trace/blob/master/docs/specs/KV/remote-service-call.md#remote-service-call
See also: https://swicloud.atlassian.net/browse/AO-7047
=> AO-7047: add Spec KV to RPC/HTTP/Cache event

v1/ao/internal/host/host.go, v1/ao/internal/host/sys_linux.go
The test results:
distro_1  | Distro is: Ubuntu 18.04.2 LTS
distro_1  | Distro is: Alpine Linux 3.9
distro_1  | Distro is: openSUSE Leap 15.0
distro_1  | Distro is: Debian GNU/Linux 8 (jessie)
distro_1  | Distro is: Amazon Linux release 2 (Karoo)
distro_1  | Distro is: Red Hat Enterprise Linux Server release 7.6 (Maipo)  _(with oraclelinux image)_
=> AO-12194: Fix distro info in metrics messages

v1/ao/internal/config/config.go, v1/ao/internal/config/config_test.go, v1/ao/internal/utils/version.go
- Rename the transaction filtering setting name to keep it consistent among all language agents.
- Update version number to v1.6.1
=> AO-12116: [transaction setting] Rename transaction filtering settings

v1/ao/trace.go, v1/ao/trace_test.go
This PR adds a new method `LoggableTraceID()` to the `ao.Trace` interface`. It can be used to fetch the loggable trace ID of the trace.
The loggable trace ID is in the following format:
`trace ID` + `-` + `sampled flag (0|1)`
=> AO-12331: Manual Log Injection

v1/ao/layer.go
This should reduce the memory overhead of having a trace containing spans that have lots of child spans.
=> Store span.childEdges as []string rather than []reporter.Context

v1/ao/client_layer.go, v1/ao/internal/config/config.go, v1/ao/internal/config/config_test.go, v1/ao/internal/config/wrappers.go, v1/ao/internal/reporter/sql_sanitizer.go, v1/ao/internal/reporter/sql_sanitizer_test.go
The change: 
- remove literals from SQL statements reported to AO backend.
e.g., the following SQL statement:
> SELECT name FROM employees WHERE age = 37 AND firstName = 'Eric'
will be converted to:
> SELECT name FROM employees WHERE age = ? AND firstName = ?
The sanitization is configurable, see the knowledge base for more details.
=> AO-7048: SQL sanitization

v1/ao/internal/reporter/sql_sanitizer.go, v1/ao/internal/reporter/sql_sanitizer_test.go, v1/ao/internal/utils/version.go
Add support to the following PostgreSQL string formats:
Bit-String: ... where name = B'0101'
Hex-String: ... where name = X'FEFF'
String constants with Unicode escapes: ... where name = U&'d\0061t+000061'
Dollar-Quoted String Constants: ... where name = $optionalTag$Dianne's horse$optionalTag$
=> [SQLSanitizationPlus] Sanitize more literal formats

Makefile, examples/appoptics-config.yaml, examples/distributed_app/alice/main_test.go, v1/ao/http_instrumentation.go, v1/ao/http_instrumentation_oboe_test.go, v1/ao/http_instrumentation_test.go, v1/ao/internal/config/config.go, v1/ao/internal/config/config_test.go, v1/ao/internal/config/wrappers.go, v1/ao/internal/metrics/metrics.go, v1/ao/internal/metrics/metrics_test.go, v1/ao/internal/reporter/context.go, v1/ao/internal/reporter/context_test.go, v1/ao/internal/reporter/event.go, v1/ao/internal/reporter/event_test.go, v1/ao/internal/reporter/oboe.go, v1/ao/internal/reporter/oboe_test.go, v1/ao/internal/reporter/reporter.go, v1/ao/internal/reporter/reporter_grpc.go, v1/ao/internal/reporter/reporter_udp.go, v1/ao/internal/reporter/test_reporter.go, v1/ao/layer.go, v1/ao/layer_test.go, v1/ao/trace.go, v1/ao/trigger_trace_test.go, v1/contrib/aogrpc/interceptors.go
Added support for headers `X-Trace-Options/X-Trace-Options-Signature` to let users trigger a trace explicitly. 
See https://swicloud.atlassian.net/browse/AO-13526 for mode details.
=> AO-13526: Trigger Trace

v1/ao/internal/config/env.go, v1/ao/internal/config/env_test.go, v1/ao/internal/utils/version.go
This PR proposes the change that accepts `enabled` and `disabled` as legit values for boolean configuration items in env vars and config files. This makes the env vars more consistent across agents.
See also: https://swicloud.atlassian.net/browse/AO-13872 for more details.
=> AO-13872: Accept enabled/disabled as valid bool values in env vars and config files

v1/ao/agent.go, v1/ao/agent_test.go, v1/ao/internal/config/config_test.go, v1/ao/internal/host/host_test.go, v1/ao/internal/host/observer_test.go, v1/ao/internal/log/logging.go, v1/ao/internal/log/logging_test.go, v1/ao/internal/metrics/metrics_test.go, v1/ao/internal/reporter/reporter_test.go
The changes:
- Use microsecond precision for logging timestamp
- Use a standalone logger, rather than the global one, to avoid interfering with other modules
See https://swicloud.atlassian.net/browse/AO-14101
=> AO-14101: [logging] logger improvements

v1/ao/internal/reporter/oboe.go, v1/ao/internal/reporter/oboe_test.go, v1/ao/internal/utils/status.go
This PR adds 3 missing KVs to the `__Init` message:
`Go.InstallDirectory`, `Go.InstallTimestamp` and `Go.LastRestart`
See https://swicloud.atlassian.net/browse/AO-9089 for more details.
=> AO-9089: Add missing KVs to the __Init message

v1/ao/internal/reporter/context.go, v1/ao/internal/reporter/oboe.go, v1/ao/trace.go
This PR improves the HTTP span processing, avoids the recording of the span and populating the transaction name when the request is disabled from tracing.
See https://swicloud.atlassian.net/browse/AO-14595
=> AO-14595: Avoid recording HTTP span when the trace is disabled

README.md
This PR removes some unnecessary configuration descriptions from the README. This makes it easier to begin with.
See https://swicloud.atlassian.net/browse/AO-15003 for the details
=> AO-15003: Show less configurations in README

v1/ao/internal/reporter/reporter_grpc.go, v1/ao/internal/reporter/reporter_test.go
This PR makes everything be sent out from a single gRPC connection, rather than two.
See https://swicloud.atlassian.net/browse/AO-14938
=> AO-14938: One gRPC client for all

v1/ao/internal/reporter/reporter_grpc.go
Enable gzip compression for the gRPC connection.
See https://swicloud.atlassian.net/browse/AO-15467
=> AO-15467: Enable gzip compression for gRPC by default

v1/ao/internal/config/config.go, v1/ao/internal/config/config_test.go, v1/ao/internal/config/wrappers.go, v1/ao/internal/reporter/reporter_grpc.go, v1/ao/internal/reporter/reporter_test.go
Remove the insecureSkipVerify option from the agent as it's no longer needed.
See https://swicloud.atlassian.net/browse/AO-15694
=> AO-15694: Remove skip verify option

v1/ao/internal/metrics/metrics.go, v1/ao/internal/reporter/reporter_test.go, v1/ao/metrics.go
The `count` in the reported metrics should always be positive.
See https://swicloud.atlassian.net/browse/AO-16200
=> AO-16200: Metrics count should be positive

v1/ao/internal/utils/version.go
With the following PRs:
- Enable gRPC compression by default: https://github.com/appoptics/appoptics-apm-go/pull/140
- Remove skip verify option: https://github.com/appoptics/appoptics-apm-go/pull/141
- Go versions support: Add Go 1.14, remove 1.12: https://github.com/appoptics/appoptics-apm-go/pull/142
- Metrics count should be positive only: https://github.com/appoptics/appoptics-apm-go/pull/143
=> AO-16200: Release v1.13.1

v1/ao/http_instrumentation.go, v1/ao/internal/metrics/metrics.go, v1/ao/layer.go, v1/ao/layer_test.go, v1/ao/trace.go
Two changes:
1. Set the transaction name when creating a new trace
2. Use a default transaction name ("custom-<top span name>") if it's not set.
See also: https://swicloud.atlassian.net/browse/AO-17468
=> AO-17468: Transaction name improvements

Makefile, v1/ao/internal/reporter/oboe.go, v1/ao/internal/reporter/oboe_test.go
This PR fixes the SampleCount request counter to align it with the spec.
See also: https://github.com/librato/trace/blob/master/docs/specs/request-counters.md
=> AO-17722: Fix SampleCount 

v1/ao/internal/config/validators.go, v1/ao/internal/config/validators_test.go
An issue is found during the tests that after the service key check is lifted for lambda, the service key masking may panic due to invalid array index access.
=> AO-16881: service name might be absent

v1/ao/internal/config/config.go, v1/ao/internal/config/config_test.go, v1/ao/internal/config/env.go, v1/ao/internal/config/env_test.go, v1/ao/internal/config/validators.go
Process invalid token bucket configurations as per the spec.
- use the default value when the config is of an invalid type (e.g., string)
- set it to the upper limit when the config value is out of range.
=> AO-16881: Process invalid bucket config

v1/ao/internal/reporter/log_writer.go
Diagnostic log for oversize message in the Lambda reporter.
See also: https://swicloud.atlassian.net/browse/AO-19383
=> AO-19383: Diagnostic log for oversize message

v1/ao/internal/reporter/context.go, v1/ao/internal/reporter/context_test.go
Let's consider all-zero task ID as invalid.
See also https://swicloud.atlassian.net/browse/AO-18826
=> AO-18826: Reject all-zero task id

v1/ao/http_client_instrumentation.go
Add a KV `HTTPMethod` to the http client span to make it show properly on the remote services UI.
See also: https://swicloud.atlassian.net/browse/AO-19983
=> AO-19983: Add HTTPMethod to the http client span

.github/workflows/test.yaml, go.mod, go.sum, v1/ao/context_test.go
Add go1.16 to the test matrix.
See also https://swicloud.atlassian.net/browse/AO-19984
=> AO-19984: Add go1.16 to the test matrix
