- v1/ao/internal/reporter/metrics_linux.go
- v1/ao/internal/reporter/metrics_linux_test.go
- v1/ao/internal/reporter/metrics_nonlinux.go
- v1/ao/internal/reporter/reporter_grpc_test.go
- v1/ao/internal/reporter/reporter_udp.go
I noticed in #13 and #14 that some of the tests are flaky due to differences in Travis resources deployed (?) and hope to fix any failures that are caught here.
> Add copyright declaration to new files

- v1/ao/internal/reporter/reporter_grpc.go
Instead perform these in the eventSender() and statusSender() routines.
This way the init routine doesn't block the app if there is a connection
issue.
https://swicloud.atlassian.net/browse/AO-7381
> AO-7381: take sending of connection init message off the init routine

- README.md
Update README.md for a simple guide of custom transaction names
> AO-8602: Update the README for custom transaction names

- v1/ao/internal/reporter/metrics.go
- v1/ao/internal/reporter/metrics_test.go
See https://swicloud.atlassian.net/browse/AO-8909
> AO-8909: Report kubepods id in the KV `DockerContainerID`

- v1/ao/internal/reporter/metrics.go
- v1/ao/internal/reporter/metrics_linux.go
- v1/ao/internal/reporter/metrics_test.go
See https://swicloud.atlassian.net/browse/AO-9021
> AO-9021 synchronize MAC address retrieval logic with other agents

- v1/ao/internal/reporter/noboe.go
- v1/ao/internal/reporter/oboe.go
- v1/ao/internal/reporter/oboe_test.go
- v1/ao/internal/reporter/reporter_grpc.go
Fix this issue: https://swicloud.atlassian.net/browse/AO-8972
> AO-8972: delete expired settings

- v1/ao/internal/host/host.go
- v1/ao/internal/host/host_test.go
- v1/ao/internal/host/observer.go
- v1/ao/internal/reporter/reporter.go
- v1/ao/internal/reporter/reporter_grpc.go
- v1/ao/internal/reporter/reporter_test.go
- v1/ao/internal/reporter/reporter_udp.go
- v1/ao/internal/reporter/test_reporter.go
- v1/ao/trace.go
Merge changes for AO-9809 to the master. The changes were merged from `ao-9809` to `ao-9808` first as there are quite a few conflicts.
It has been reviewed in https://github.com/appoptics/appoptics-apm-go/pull/61
> AO-9809: update with ao-9809 changes

- README.md
- v1/ao/agent.go
- v1/ao/http_instrumentation.go
- v1/ao/internal/config/config.go
- v1/ao/internal/config/config_test.go
- v1/ao/internal/config/reporter.go
- v1/ao/internal/config/wrappers.go
- v1/ao/internal/host/host.go
- v1/ao/internal/host/host_test.go
- v1/ao/internal/reporter/oboe.go
- v1/ao/internal/reporter/oboe_test.go
- v1/ao/internal/reporter/reporter.go
- v1/ao/internal/reporter/reporter_grpc.go
- v1/ao/internal/reporter/reporter_test.go
- v1/ao/internal/reporter/reporter_udp.go
- v1/ao/trace.go
Added an environment variable `APPOPTICS_DISABLED`. The agent will be disabled when its value is `true`
Ref: https://swicloud.atlassian.net/browse/AO-9958
> AO-9958: disable agent flag

- v1/ao/http_instrumentation_test.go
- v1/ao/internal/reporter/metrics.go
- v1/ao/internal/reporter/noboe.go
- v1/ao/internal/reporter/oboe.go
- v1/ao/internal/reporter/reporter.go
- v1/ao/internal/reporter/reporter_grpc.go
Ref: https://swicloud.atlassian.net/browse/AO-8614
fix a data race issue of updateSetting and getSetting
> AO-8614: fix updateSetting and getSetting

- v1/ao/internal/reporter/reporter_grpc.go
Ref: https://swicloud.atlassian.net/browse/AO-10072
When the collector returns `ResultCode_REDIRECT` it should also bring the new address for redirection in the `Arg` field.
This PR adds a simple check to make sure the `Arg` is not empty. Normally it would not happen.
It also slightly moved the place where the redirect counter is increased to exactly follow the meaning of `maximum number of redirections`.  There is no spec for the number though.
> AO-10072: check the Arg on ResultCode_REDIRECT

- v1/ao/internal/utils/version.go
Update the version to 1.4.0 and release it.
> Update version to 1.4.0

- v1/ao/internal/config/config.go
- v1/ao/internal/config/config_test.go
- v1/ao/internal/config/validators.go
- v1/ao/internal/config/validators_test.go
- v1/ao/internal/reporter/reporter_grpc.go
Jira ticket: 
- https://swicloud.atlassian.net/browse/AO-10242
- https://swicloud.atlassian.net/browse/AO-10251
service name cleansing:
- convert all characters into lowercase
- replace spaces with hyphen
- remove invalid characters
> AO-10251: Service name cleansing

- README.md
- v1/ao/internal/config/config.go
- v1/ao/internal/config/config_test.go
- v1/ao/internal/config/validators.go
- v1/ao/internal/config/validators_test.go
- v1/ao/internal/config/wrappers.go
- v1/ao/internal/reporter/event.go
- v1/ao/internal/reporter/event_test.go
- v1/ao/internal/reporter/oboe.go
- v1/ao/internal/reporter/oboe_test.go
Negotiation is required to merge the remote settings with the local sampling config.
See https://swicloud.atlassian.net/browse/AO-11811 for more details.
> AO-11811: Trace decision sync-up

- .codecov.yaml
- .travis.yml
- v1/ao/http_instrumentation_oboe_test.go
- v1/ao/http_instrumentation_test.go
- v1/ao/internal/config/config.go
- v1/ao/internal/config/config_test.go
- v1/ao/internal/config/env.go
- v1/ao/internal/config/env_test.go
- v1/ao/internal/config/reporter.go
- v1/ao/internal/config/reporter_test.go
- v1/ao/internal/config/validators.go
- v1/ao/internal/config/validators_test.go
- v1/ao/internal/config/wrappers.go
- v1/ao/internal/config/wrappers_test.go
- v1/ao/internal/host/host.go
- v1/ao/internal/host/host_test.go
- v1/ao/internal/log/logging.go
- v1/ao/internal/log/logging_test.go
- v1/ao/internal/reporter/bytesbucket_test.go
- v1/ao/internal/reporter/event.go
- v1/ao/internal/reporter/methods_test.go
- v1/ao/internal/reporter/oboe.go
- v1/ao/internal/reporter/oboe_test.go
- v1/ao/internal/reporter/reporter.go
- v1/ao/internal/reporter/reporter_grpc.go
- v1/ao/internal/reporter/reporter_test.go
The changes made in this PR:
- added YAML config file support
- refactored the way of loading configurations
- other improvements
> AO-12135: Config file support

- .travis.yml
- v1/ao/agent.go
- v1/ao/http_instrumentation.go
- v1/ao/http_instrumentation_test.go
- v1/ao/internal/config/config.go
- v1/ao/internal/config/config_test.go
- v1/ao/internal/config/env.go
- v1/ao/internal/config/validators.go
- v1/ao/internal/config/validators_test.go
- v1/ao/internal/config/wrappers.go
- v1/ao/internal/host/observer_test.go
- v1/ao/internal/reporter/context.go
- v1/ao/internal/reporter/event.go
- v1/ao/internal/reporter/event_test.go
- v1/ao/internal/reporter/oboe.go
- v1/ao/internal/reporter/oboe_test.go
- v1/ao/internal/reporter/reporter.go
- v1/ao/internal/reporter/url.go
- v1/ao/internal/reporter/url_test.go
- v1/ao/layer.go
- v1/ao/layer_test.go
- v1/ao/trace.go
- v1/contrib/aogrpc/interceptors.go
URL-based transaction filtering support. See https://swicloud.atlassian.net/browse/AO-12116 for more details.
> AO-12116 URL-based transaction filtering

- v1/ao/internal/utils/version.go
> Version 1.6.0

- v1/ao/internal/config/validators.go
- v1/ao/internal/config/validators_test.go
- support both the legacy and new Swoken token formats
> AO-12848: Swoken token format support

- v1/ao/internal/utils/version.go
> Update version to v1.7.0

- examples/appoptics-config.yaml
and link the knowledge base to the sample config file in this repo.
See also: https://github.com/librato/ao-kb-docs/pull/779
> Add a sample config file to the examples folder

- .travis.yml
Update the Travis script to upload the report to codecov
> Fix codecov

- README.md
- examples/appoptics-config.yaml
- v1/ao/internal/config/config.go
- v1/ao/internal/config/config_test.go
- v1/ao/internal/config/validators.go
- v1/ao/internal/config/wrappers.go
- v1/ao/internal/host/observer.go
See https://swicloud.atlassian.net/browse/AO-11860
> AO-11860: Configurable EC2 metadata retrieval timeout

- README.md
- v1/ao/internal/config/config.go
- v1/ao/internal/config/config_test.go
- v1/ao/internal/reporter/reporter_grpc.go
Make APPOPTICS_INSECURE_SKIP_VERIFY default to true.
See https://swicloud.atlassian.net/browse/AO-13786
> AO-13786: APPOPTICS_INSECURE_SKIP_VERIFY default to true

- Makefile
- v1/ao/internal/config/config_test.go
- v1/ao/internal/reporter/reporter_grpc.go
- v1/ao/internal/reporter/reporter_test.go
See https://swicloud.atlassian.net/browse/AO-14067
> AO-14067: Fix vet warnings

- v1/ao/internal/utils/version.go
This PR just bumps up the version for custom metrics
See also https://swicloud.atlassian.net/browse/AO-7049 for more details.
> AO-7049: Bump up version for custom metrics

- .travis.yml
- README.md
- v1/ao/agent.go
- v1/ao/http_instrumentation.go
- v1/ao/internal/config/config.go
- v1/ao/internal/config/config_test.go
- v1/ao/internal/config/wrappers.go
- v1/ao/internal/host/host_test.go
- v1/ao/internal/reporter/reporter.go
- v1/ao/internal/reporter/reporter_grpc.go
- v1/ao/internal/reporter/reporter_test.go
- v1/ao/internal/reporter/sql_sanitizer_test.go
- v1/ao/layer_test.go
- v1/ao/trace.go
The logs are suppressed when the agent is disabled.
See https://swicloud.atlassian.net/browse/AO-14774
> AO-14774: Suppress logs when the agent is disabled

- v1/ao/internal/reporter/methods.go
- v1/ao/internal/reporter/reporter_grpc.go
- v1/ao/internal/utils/version.go
Made some improvements to the logging and also bumped up the version to v1.12.0
> AO-14725: Logs improving

- examples/appoptics-config.yaml
This PR adds the configuration options for the HTTP/HTTPS proxy.
See the Jira ticket for more details: https://swicloud.atlassian.net/browse/AO-14627
See also: https://github.com/librato/ao-kb-docs/pull/909
> AO-14627: Add proxy config

- v1/ao/internal/config/config.go
- v1/ao/internal/config/config_test.go
- v1/ao/internal/config/wrappers.go
- v1/ao/internal/metrics/metrics.go
- v1/ao/internal/metrics/metrics_test.go
- v1/ao/internal/reporter/reporter_grpc.go
This PR adds runtime metrics to the agent.
See https://swicloud.atlassian.net/browse/AO-7052 for more details.
> AO-7052: Report runtime metrics

- v1/ao/internal/utils/version.go
Make a release for runtime metrics
> AO-7052: Bump version to v1.13.0

- .travis.yml
- README.md
Try Go 1.14 support.
See https://swicloud.atlassian.net/browse/AO-15732
> AO-15732: Move forward to Go 1.14

- v1/ao/http_instrumentation.go
- v1/ao/http_instrumentation_test.go
- v1/ao/internal/config/config.go
- v1/ao/internal/config/config_test.go
- v1/ao/internal/config/wrappers.go
- v1/ao/layer.go
This PR adds some KVs required in the webserver spec.
See also: https://swicloud.atlassian.net/browse/AO-17525
> AO-17525: ws spec

- v1/ao/internal/metrics/metrics.go
- v1/ao/internal/reporter/context.go
This PR makes some changes to the trace event KVs and the metrics to follow the spec on SampleRate and SampleSource.
> AO-17878: update trace event KVs and metrics fields

- v1/ao/internal/config/config.go
- v1/ao/internal/config/config_test.go
- v1/ao/internal/config/validators.go
- v1/ao/internal/reporter/reporter.go
- v1/ao/trace.go
Let the reporter mode decision happen in a single place.
> AO-16881: Reporter mode check in a single point

- v1/ao/internal/utils/version.go
- v1/contrib/lambda/go.mod
This version adds support to the AWS Lambda.
> AO-16881: Bump version to 1.14.0

- LICENSE
Move from Librato license to Apache license 2.0
> AO-17771: Change license to Apache 2.0

- v1/ao/internal/reporter/oboe.go
- v1/ao/internal/reporter/oboe_test.go
Put the `ThroughTraceCount` metric in the right place.
> AO-17722: Update ThroughTraceCount

- README.md
As titled, change the support email address to technicalsupport@solarwinds.com
> AO-20159: Update support email address

- v1/ao/internal/config/config.go
- v1/ao/internal/config/config_test.go
- v1/ao/internal/reporter/reporter_grpc.go
* Update default collector to point to apm-collector.dc-01.st-ssp.solarwinds.com
* NH-1257
* Used examples/sample_app and unit testing
> NH-1257: change default collector to apm-collector.dc-01.st-ssp.solarwinds.com

- v1/ao/internal/config/config.go
- v1/ao/internal/config/config_test.go
- v1/ao/internal/reporter/reporter_grpc.go
Reverts appoptics/appoptics-apm-go#181
> Revert "NH-1257: change default collector to apm-collector.dc-01.st-ssp.solarwinds.com"
